# deploy.yml
name: Build and Deploy Hugo Site

on:
  push:
    branches:
      - main # Set this to your main publishing branch

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to push the 'public' folder

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
          
      # Step 3: Deploy the 'public' folder to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          # Deploy to the 'gh-pages' branch
          publish_branch: gh-pages
